# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

default_platform(:android)

platform :android do
  desc "Submit a new Internal Build to Play Store"
  lane :internal do
    gradle(
      task: "clean bundleRelease"
    )
    upload_to_play_store(
      track: 'internal',
      aab: './app/build/outputs/bundle/release/app-release.aab',
      json_key: 'service-account.json',
      skip_upload_metadata: false,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
      task: "clean bundleRelease"
    )
    upload_to_play_store(
      track: 'production',
      aab: './app/build/outputs/bundle/release/app-release.aab',
      json_key: 'service-account.json',
      skip_upload_metadata: false,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Upload metadata only"
  lane :metadata do
    upload_to_play_store(
      track: 'internal',
      json_key: 'service-account.json',
      skip_upload_aab: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end 